### PR TITLE
Feat/navigation and permissions

### PR DESCRIPTION
**Pull request by andrewschmidgit**

### CODE REVIEW

**Comment by gautamnabin5** [comment]
Its not up to date with master, and failing the tests for some reason

**Comment by gautamnabin5** [comment]
Its not up to date with master, and failing the tests for some reason

**Comment by gman4455** [comment]
It's because the cucumber tests are failing. Most of the tests were written assuming the user didn't need to be logged in. We'll need to add a dummy "login" step

**Comment by gman4455** [comment]
If you click the 'x' and then click details, you should be able to see the details of why it failed.

**Comment by gman4455** [comment]
Pushed some changes, but some tests still appear to be broken. Seems to be related to the cucumber tests for users. Most of the time the `access_code` thing.

**Pull request merged**
